AllCops:
  DefaultFormatter: fuubar
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

Style/CaseIndentation:
  IndentOneStep: true

Style/DoubleNegation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SignalException:
  EnforcedStyle: only_raise

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/AccessorMethodName:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CaseIndentation:
  IndentWhenRelativeTo: end
  IndentOneStep: true

Style/SpaceBeforeFirstArg:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/EndAlignment:
  AlignWith: variable
  AutoCorrect: true

# -=-=-=-=-=- TODO -=-=-=-=-=- #

Metrics/ClassLength:
  Max: 999

Metrics/LineLength:
  Max: 999

Metrics/MethodLength:
  Max: 999

Metrics/ModuleLength:
  Max: 999

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Max: 135

Metrics/PerceivedComplexity:
  Max: 16
